// models.rs

use uniffi::Enum;
use thiserror::Error;
// Импорт общих ошибок
use crate::core::core::CoreError;

// --- Управление ресурсами/ошибками ---
// Единая структура ошибок для FFI-границы.
#[derive(Debug, Error)]
pub enum TranslateError {
    #[error("Translation failed: {message}")]
    RequestError { message: String },
    
    #[error("The target language cannot be Auto")]
    TargetLanguageAuto,

    // [ИЗМЕНЕНО] Обобщенная ошибка из `core`
    #[error("Core network/IO error: {message}")]
    CoreError { message: String },
    
    // (Rule 2.2) Ошибка для перехвата паники
    #[error("The FFI function panicked: {message}")]
    Panic { message: String },
}

// [НОВОЕ] (Rule 2.3)
// Реализация From для автоматического преобразования CoreError
// в нашу специфичную TranslateError.
impl From<CoreError> for TranslateError {
    fn from(e: CoreError) -> Self {
        TranslateError::CoreError { message: e.to_string() }
    }
}


// Language enum (без изменений)
#[derive(Debug, Clone, Copy, Enum)]
pub enum Language {
    Auto,
    Afrikaans,
    Albanian,
    Amharic,
    Arabic,
    Armenian,
    Azerbaijani,
    Basque,
    Belarusian,
    Bengali,
    Bosnian,
    Bulgarian,
    Catalan,
    Cebuano,
    Chichewa,
    ChineseSimplified,
    ChineseTraditional,
    Corsican,
    Croatian,
    Czech,
    Danish,
    Dutch,
    English,
    Esperanto,
    Estonian,
    Filipino,
    Finnish,
    French,
    Frisian,
    Galician,
    Georgian,
    German,
    Greek,
    Gujarati,
    HaitianCreole,
    Hausa,
    Hawaiian,
    HebrewIw, // Hebrew1 in Kotlin
    HebrewHe, // Hebrew2 in Kotlin
    Hindi,
    Hmong,
    Hungarian,
    Icelandic,
    Igbo,
    Indonesian,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kazakh,
    Khmer,
    Korean,
    KurdishKurmanji,
    Kyrgyz,
    Lao,
    Latin,
    Latvian,
    Lithuanian,
    Luxembourgish,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Maori,
    Marathi,
    Mongolian,
    MyanmarBurmese,
    Nepali,
    Norwegian,
    Odia,
    Pashto,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    Samoan,
    ScotsGaelic,
    Serbian,
    Sesotho,
    Shona,
    Sindhi,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    Spanish,
    Sundanese,
    Swahili,
    Swedish,
    Tajik,
    Tamil,
    Telugu,
    Thai,
    Turkish,
    Ukrainian,
    Urdu,
    Uyghur,
    Uzbek,
    Vietnamese,
    Welsh,
    Xhosa,
    Yiddish,
    Yoruba,
    Zulu,
}

impl Language {
    /// Returns the Google Translate API code for the language.
    pub fn code(&self) -> &'static str {
        match self {
            Language::Auto => "auto",
            Language::Afrikaans => "af",
            Language::Albanian => "sq",
            Language::Amharic => "am",
            Language::Arabic => "ar",
            Language::Armenian => "hy",
            Language::Azerbaijani => "az",
            Language::Basque => "eu",
            Language::Belarusian => "be",
            Language::Bengali => "bn",
            Language::Bosnian => "bs",
            Language::Bulgarian => "bg",
            Language::Catalan => "ca",
            Language::Cebuano => "ceb",
            Language::Chichewa => "ny",
            Language::ChineseSimplified => "zh-cn",
            Language::ChineseTraditional => "zh-tw",
            Language::Corsican => "co",
            Language::Croatian => "hr",
            Language::Czech => "cs",
            Language::Danish => "da",
            Language::Dutch => "nl",
            Language::English => "en",
            Language::Esperanto => "eo",
            Language::Estonian => "et",
            Language::Filipino => "tl",
            Language::Finnish => "fi",
            Language::French => "fr",
            Language::Frisian => "fy",
            Language::Galician => "gl",
            Language::Georgian => "ka",
            Language::German => "de",
            Language::Greek => "el",
            Language::Gujarati => "gu",
            Language::HaitianCreole => "ht",
            Language::Hausa => "ha",
            Language::Hawaiian => "haw",
            Language::HebrewIw => "iw", // Hebrew1
            Language::HebrewHe => "he", // Hebrew2
            Language::Hindi => "hi",
            Language::Hmong => "hmn",
            Language::Hungarian => "hu",
            Language::Icelandic => "is",
            Language::Igbo => "ig",
            Language::Indonesian => "id",
            Language::Irish => "ga",
            Language::Italian => "it",
            Language::Japanese => "ja",
            Language::Javanese => "jw",
            Language::Kannada => "kn",
            Language::Kazakh => "kk",
            Language::Khmer => "km",
            Language::Korean => "ko",
            Language::KurdishKurmanji => "ku",
            Language::Kyrgyz => "ky",
            Language::Lao => "lo",
            Language::Latin => "la",
            Language::Latvian => "lv",
            Language::Lithuanian => "lt",
            Language::Luxembourgish => "lb",
            Language::Macedonian => "mk",
            Language::Malagasy => "mg",
            Language::Malay => "ms",
            Language::Malayalam => "ml",
            Language::Maltese => "mt",
            Language::Maori => "mi",
            Language::Marathi => "mr",
            Language::Mongolian => "mn",
            Language::MyanmarBurmese => "my",
            Language::Nepali => "ne",
            Language::Norwegian => "no",
            Language::Odia => "or",
            Language::Pashto => "ps",
            Language::Persian => "fa",
            Language::Polish => "pl",
            Language::Portuguese => "pt",
            Language::Punjabi => "pa",
            Language::Romanian => "ro",
            Language::Russian => "ru",
            Language::Samoan => "sm",
            Language::ScotsGaelic => "gd",
            Language::Serbian => "sr",
            Language::Sesotho => "st",
            Language::Shona => "sn",
            Language::Sindhi => "sd",
            Language::Sinhala => "si",
            Language::Slovak => "sk",
            Language::Slovenian => "sl",
            Language::Somali => "so",
            Language::Spanish => "es",
            Language::Sundanese => "su",
            Language::Swahili => "sw",
            Language::Swedish => "sv",
            Language::Tajik => "tg",
            Language::Tamil => "ta",
            Language::Telugu => "te",
            Language::Thai => "th",
            Language::Turkish => "tr",
            Language::Ukrainian => "uk",
            Language::Urdu => "ur",
            Language::Uyghur => "ug",
            Language::Uzbek => "uz",
            Language::Vietnamese => "vi",
            Language::Welsh => "cy",
            Language::Xhosa => "xh",
            Language::Yiddish => "yi",
            Language::Yoruba => "yo",
            Language::Zulu => "zu",
        }
    }
}
